name: code quality

on:
  workflow_call:

jobs:

  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    steps:

      - name: code checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: install eslint + parser
        run: npm install --save-dev eslint@9 @eslint/js@9 @babel/eslint-parser @babel/preset-react --legacy-peer-deps

      - name: install dependencies
        run: |
          npm install
          npm run

      - name: run lint
        run: npm run lint

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          # Use 'javascript-typescript' to cover all Node.js/JS/TS files
          languages: javascript-typescript

      - name: Perform Analysis (SAST)
        uses: github/codeql-action/analyze@v4
