name: dependency scan

on: 
  workflow_call:

jobs:
 
  dependencies-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
     
      - name: code checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: dependencies check
        run: npm audit


