name: deploy to server

on: 
  workflow_call:

jobs:

  deploy:
    #env:
      #DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
    runs-on: ubuntu-latest
      
    steps:
      
      - name: checkout code
        uses: actions/checkout@v5

      - name: Shorten github sha
        run: echo "DOCKER_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: ssh to server and install dependencies
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export DEBIAN_FRONTEND=noninteractive
            echo "Installing required packages"
            sudo apt-get update -y
            sudo apt-get install docker.io -y
            sudo apt-get install ca-certificates curl gnupg

            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg

            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            sudo apt-get update -y
            
            sudo apt-get install docker-compose-plugin -y

            sudo usermod -aG docker $USER
            newgrp docker
            
            mkdir -p devsecops

            echo "Docker setup complete"

      - name: Create .env file from secrets
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> mern.env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> mern.env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}" >> db.env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> db.env

      - name: Copy the docker-compose & env files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml,*.env"
          target: ~/devsecops

      - name: SSH to server & run the app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
            export DOCKER_TAG=${{ env.DOCKER_TAG }}
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login  --username ${{ vars.DOCKERHUB_USER }} --password-stdin
            cd ~/devsecops
            docker compose down
            docker system prune -f
            docker compose up -d --build --pull always
            echo "App Running"


