name: dockerfile validate

on:
  workflow_call:

jobs:

  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [backend, frontend]

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
     
      - name: checkout code
        uses: actions/checkout@v5

      - name: validate dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.folder }}/Dockerfile
      
