name: trivy image scan

on: 
  workflow_call:

jobs:

  scan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        folder: [backend, frontend]

    steps:
        
      - name: codechekout
        uses: actions/checkout@v5

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Shorten github sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Trivy scanner
        uses: aquasecurity/trivy-action@0.35.0
        with: 
          image-ref: ${{ vars.DOCKERHUB_USER }}/mern-${{ matrix.folder }}:${{ env.SHORT_SHA }}
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          trivyignores: ${{ github.workspace }}/.trivyignore
