name: Secrets Scan

on:
  workflow_call:

jobs:

  secrets-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [backend, frontend]

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:

      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run gitleakes scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_REPORT_ARTIFACT_NAME: gitleaks-${{ matrix.folder }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
